image_url_file: image_urls.txt
download_directory: ./downloads/
batch_size: 2
min_wait_time: 0.8
max_wait_time: 3.0
max_image_size_mb: MAX
replace_downloaded_file_size: true
skip_if_file_exists: false
